### PR TITLE
Add precommit config

### PR DESCRIPTION
**Pull request by tumido**
- Pull precommit config from thoth-template https://github.com/thoth-station/template-project/blob/master/.pre-commit-config.yaml
- Add hooks for llinting and checking Jupyter Notebooks:
  - Flake8 for notebooks - `flake8-nb`: https://github.com/s-weigand/flake8-nb
  - Black for notebooks - `black-nb`: https://github.com/tomcatling/black-nb

These 2 hooks above should in theory sufficiently replace the original `flake8` and `black`, because they are executing them anyways, but it didn't work for me - it didn't fix the issues in original "just python" files.

And as a bonus, reformat and fix found violations in the template, so precommit is passing.

### CODE REVIEW

**Comment by tumido** [comment]
@harshad16 can you please help me with the precommit error? I've tried installing a new hook to provide linting for Jupyter notebooks, but sesheta doesn't like it for some reason. Works just fine locally.

**Comment by harshad16** [comment]
> @harshad16 can you please help me with the precommit error? I've tried installing a new hook to provide linting for Jupyter notebooks, but sesheta doesn't like it for some reason. Works just fine locally.

@tumido  surely, will take a look at this and get back to you on this.

**Comment by s-weigand** [comment]
@tumido `flake8-nb` author here, the hook supports `*.py` **AND** `*.ipynb` since version `0.2.3`, hope like that it works. 😄 
Also, you might want to run `pre-commit autoupdate`, to get all hooks up to date. 😉

**Comment by tumido** [comment]
@s-weigand love it! It works flawlessly. :raised_hands: You sir, saved us some time (and electricity) on each CI run now... What a simple change, but what difference it can make.

Thank you for your comment, I wouldn't notice your release for a bit. :smile: And thank you for `flake8_nb`. It's really handy I must say. :+1:

**Comment by tumido** [comment]
@durandom wdyt? merge/nomerge that's the question of the day. :smile:

**Comment by s-weigand** [comment]
@tumido You are welcome and I'm glad my tool is used by someone besides me 😋

**Review by durandom — APPROVED** [review]
I ❤️ pre-commit hooks, especially that we now can even bug our DS folks to write clean code😈 

/cc @martinpovolny

**Pull request merged**
