### PR TITLE
Automation bootstrap base with Kustomize

### PR DESCRIPTION
**Pull request by tumido**
Reincarnation of #2  because a you can't stop me by closing a PR.

Add automation manifests bootstrap code to the template repo.

Uses Kustomize and Ksops, allows for both custom and Argo-CD deployment. Contains also a step by step setup guide.

### CODE REVIEW

**Comment by tumido** [comment]
@durandom  we don't use Argo CD for the `sme-mailinglist` just yet. I wanted to have Argo deployed via Argo CD first. See: https://github.com/AICoE/aicoe-sre/pull/6 

Current automation for the SME project uses simple directly submittable Argo workflow as (partially) described in the [README](https://github.com/aicoe-aiops/openshift-sme-mailing-list-analysis/blob/master/argo/README.md). This is a temporary solution and it should be converted to Argo CD deployable scheme based on this PR. See: https://github.com/aicoe-aiops/openshift-sme-mailing-list-analysis/pull/3

**Comment by tumido** [comment]
I think this PR is cursed. :zap: 

@durandom's pretty sure he didn't close it, but GitHub thinks he did. And there's no reopen button anywhere for neither of us and API says `state cannot be changed. The pull request cannot be reopened.` :exploding_head: 

Let's try resubmitting this for the third time and try to merge it before gods notices that new PR and tries to close it again. :smirk: :smile:

**Comment by tumido** [comment]
Ha! It worked! @durandom 

Lesson learned: If the repo is private, all its forks are private as well. If the upstream gets converted to a public repo, it doesn't make the forks public. And for some reason you can't contribute from a private fork to a public upstream. When I've tried resubmitting this PR, it didn't allow me to open the PR against the upstream repo at all. Like that the upstream to this repo never existed... When I've changed my fork to be a public repo, it enabled the "Reopen pull request" button here. 

:exploding_head:  What a day.. :boom:

**Comment by tumido** [comment]
I don't think I need any other reviews here. I would rather merge this before it's closed again. :smile: 

If @HumairAK has any concerns later, he can ping me directly and we'll figure it out :slightly_smiling_face:

**Comment by durandom** [comment]
quick quick merge merge

**Pull request merged**
